# Generated by Django 3.2.4 on 2021-08-04 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_rename_movie_song_album'),
        ('Accounts', '0003_favourite_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='song',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='UserApp.song'),
        ),
    ]
