# Generated by Django 3.2.4 on 2021-08-01 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Movie',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='songimages')),
                ('file', models.FileField(upload_to='songfiles')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserApp.movie')),
            ],
            options={
                'db_table': 'Song',
            },
        ),
    ]
