# Generated by Django 3.2.4 on 2021-08-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Album',
        ),
    ]
