# Generated by Django 3.2.5 on 2021-08-02 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_rename_movie_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='movie',
            new_name='album',
        ),
    ]
